
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/snap/cmake/1479/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/armin/.local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/c/Program Files/Docker/Docker/resources/bin/"
      - "/mnt/c/Users/Reset PC/bin/"
      - "/mnt/c/Program Files/Git/mingw64/bin/"
      - "/mnt/c/Program Files/Git/usr/local/bin/"
      - "/mnt/c/Program Files/Git/usr/bin/"
      - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.8/bin/"
      - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.8/libnvvp/"
      - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/bin/"
      - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/libnvvp/"
      - "/mnt/c/Python312/Scripts/"
      - "/mnt/c/Python312/"
      - "/mnt/c/Python313/Scripts/"
      - "/mnt/c/Python313/"
      - "/mnt/c/Program Files/Eclipse Adoptium/jdk-17.0.14.7-hotspot/bin/"
      - "/mnt/c/WINDOWS/system32/"
      - "/mnt/c/WINDOWS/"
      - "/mnt/c/WINDOWS/System32/Wbem/"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/WINDOWS/System32/OpenSSH/"
      - "/mnt/c/Program Files/nodejs/"
      - "/mnt/c/ProgramData/chocolatey/bin/"
      - "/mnt/c/Program Files/Git/cmd/"
      - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR/"
      - "/mnt/c/Program Files/NVIDIA Corporation/Nsight Compute 2025.1.1/"
      - "/mnt/c/Users/Reset PC/AppData/Local/Programs/cursor/resources/app/bin/"
      - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "/mnt/c/Program Files/LLVM/bin/"
      - "/mnt/c/Program Files (x86)/LLVM/bin/"
      - "/mnt/c/Program Files/CMake/bin/"
      - "/mnt/c/Users/Reset PC/.cargo/bin/"
      - "/mnt/c/Users/Reset PC/AppData/Local/Microsoft/WindowsApps/"
      - "/mnt/c/Users/Reset PC/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "/mnt/c/Users/Reset PC/AppData/Roaming/npm/"
      - "/mnt/c/Program Files/Git/usr/bin/vendor_perl/"
      - "/mnt/c/Program Files/Git/usr/bin/core_perl/"
      - "/snap/bin/"
    searched_directories:
      - "/home/armin/.local/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/armin/.local/bin"
        - "/home/armin/.local/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/c/Program Files/Docker/Docker/resources/bin"
        - "/mnt/c/Users/Reset PC/bin"
        - "/mnt/c/Program Files/Git/mingw64/bin"
        - "/mnt/c/Program Files/Git/usr/local/bin"
        - "/mnt/c/Program Files/Git/usr/bin"
        - "/mnt/c/Program Files/Git/usr/bin"
        - "/mnt/c/Program Files/Git/mingw64/bin"
        - "/mnt/c/Program Files/Git/usr/bin"
        - "/mnt/c/Users/Reset PC/bin"
        - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.8/bin"
        - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.8/libnvvp"
        - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/bin"
        - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/libnvvp"
        - "/mnt/c/Python312/Scripts"
        - "/mnt/c/Python312"
        - "/mnt/c/Python313/Scripts"
        - "/mnt/c/Python313"
        - "/mnt/c/Program Files/Eclipse Adoptium/jdk-17.0.14.7-hotspot/bin"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0"
        - "/mnt/c/WINDOWS/System32/OpenSSH"
        - "/mnt/c/Program Files/nodejs"
        - "/mnt/c/ProgramData/chocolatey/bin"
        - "/mnt/c/Program Files/Git/cmd"
        - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common"
        - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR"
        - "/mnt/c/Program Files/NVIDIA Corporation/Nsight Compute 2025.1.1"
        - "/mnt/c/Users/Reset PC/AppData/Local/Programs/cursor/resources/app/bin"
        - "/mnt/c/Program Files/Docker/Docker/resources/bin"
        - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit"
        - "/mnt/c/Program Files/LLVM/bin"
        - "/mnt/c/Program Files (x86)/LLVM/bin"
        - "/mnt/c/Program Files/CMake/bin"
        - "/mnt/c/Users/Reset PC/.cargo/bin"
        - "/mnt/c/Users/Reset PC/AppData/Local/Microsoft/WindowsApps"
        - "/mnt/c/Users/Reset PC/AppData/Local/Programs/Microsoft VS Code/bin"
        - "/mnt/c/Users/Reset PC/AppData/Roaming/npm"
        - "/mnt/c/Users/Reset PC/AppData/Local/Programs/cursor/resources/app/bin"
        - "/mnt/c/Program Files/Git/usr/bin/vendor_perl"
        - "/mnt/c/Program Files/Git/usr/bin/core_perl"
        - "/snap/bin"
...
